// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  img_gallery: dynamic(() => import("./ImgGallery")),
  text_block: dynamic(() => import("./TextBlock")),
};
